"use client";

import { useStore } from "@/store/useStore";
import { STATION_NAMES, type StationCode } from "@/lib/constants";
import { motion } from "framer-motion";
import { useState } from "react";

export default function SharePlan() {
  const { recommendations, trainNo, date, from, to } = useStore();
  const [copied, setCopied] = useState(false);

  if (recommendations.length === 0 || !from || !to) return null;

  const bestPlan = recommendations[0];

  const planText = `🚄 SeatMatrix - Journey Plan
━━━━━━━━━━━━━━━━━━━━━━━━
Train: ${trainNo}
Date: ${date}
Route: ${STATION_NAMES[from as StationCode]} → ${STATION_NAMES[to as StationCode]}

📋 Recommended Plan:
${bestPlan.segments
  .map(
    (seg, i) =>
      `  ${i + 1}. Seat ${seg.seatNumber} (${seg.berth}) in ${seg.coachId}: ${seg.fromStation} → ${seg.toStation}`
  )
  .join("\n")}

${bestPlan.seatChanges > 0
  ? `⚠️ Requires ${bestPlan.seatChanges} seat switch(es)`
  : "✅ Single seat for entire journey"
}

Generated by SeatMatrix`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(planText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
      const textarea = document.createElement("textarea");
      textarea.value = planText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <motion.button
      onClick={handleCopy}
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-sm text-gray-300 hover:bg-white/10 hover:text-white transition-all"
    >
      {copied ? (
        <>
          <svg className="w-4 h-4 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
          </svg>
          Share Plan
        </>
      )}
    </motion.button>
  );
}
